config/routes.rb
Rails.application.routes.draw do

  scope "org/:org_permalink", :as => 'organization' do
    resources :domains, :only => [:index, :new, :create, :destroy] do
      match :verify, :on => :member, :via => [:get, :post]
      get :setup, :on => :member
      post :check, :on => :member
    end
    resources :servers, :except => [:index] do
      resources :domains, :only => [:index, :new, :create, :destroy] do
        match :verify, :on => :member, :via => [:get, :post]
        get :setup, :on => :member
        post :check, :on => :member
      end
      resources :track_domains do
        post :toggle_ssl, :on => :member
        post :check, :on => :member
      end
      resources :credentials
      resources :routes
      resources :http_endpoints
      resources :smtp_endpoints
      resources :address_endpoints
      resources :ip_pool_rules
      resources :messages do
        get :incoming, :on => :collection
        get :outgoing, :on => :collection
        get :held, :on => :collection
        get :activity, :on => :member
        get :plain, :on => :member
        get :html, :on => :member
        get :html_raw, :on => :member
        get :attachments, :on => :member
        get :headers, :on => :member
        get :attachment, :on => :member
        get :download, :on => :member
        get :spam_checks, :on => :member
        post :retry, :on => :member
        post :cancel_hold, :on => :member
        get :suppressions, :on => :collection
        delete :remove_from_queue, :on => :member
        get :deliveries, :on => :member
      end
      resources :webhooks do
        get :history, :on => :collection
        get 'history/:uuid', :on => :collection, :action => 'history_request', :as => 'history_request'
      end
      get :limits, :on => :member
      get :retention, :on => :member
      get :queue, :on => :member
      get :spam, :on => :member
      get :delete, :on => :member
      get 'help/outgoing' => 'help#outgoing'
      get 'help/incoming' => 'help#incoming'
      get :advanced, :on => :member
      post :suspend, :on => :member
      post :unsuspend, :on => :member
    end

    resources :ip_pool_rules
    resources :ip_pools, :controller => 'organization_ip_pools' do
      put :assignments, :on => :collection
    end
    root 'servers#index'
    get 'settings' => 'organizations#edit'
    patch 'settings' => 'organizations#update'
    get 'delete' => 'organizations#delete'
    delete 'delete' => 'organizations#destroy'
  end

  resources :organizations, :except => [:index]
  resources :users
  resources :ip_pools do
    resources :ip_addresses
  end

  get 'settings' => 'user#edit'
  patch 'settings' => 'user#update'
  post 'persist' => 'sessions#persist'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/token' => 'sessions#create_with_token'
  delete 'logout' => 'sessions#destroy'
  match 'login/reset' => 'sessions#begin_password_reset', :via => [:get, :post]
  match 'login/reset/:token' => 'sessions#finish_password_reset', :via => [:get, :post]


  get 'ip' => 'sessions#ip'

  root 'organizations#index'
end

app/controllers/messages_controller.rb
  class MessagesController < ApplicationController

  include WithinOrganization

  before_action { @server = organization.servers.present.find_by_permalink!(params[:server_id]) }
  before_action { params[:id] && @message = @server.message_db.message(params[:id].to_i) }

  def new
    if params[:direction] == 'incoming'
      @message = IncomingMessagePrototype.new(@server, request.ip, 'web-ui', {})
      @message.from = session[:test_in_from] || current_user.email_tag
      @message.to = @server.routes.order(:name).first&.description
    else
      @message = OutgoingMessagePrototype.new(@server, request.ip, 'web-ui', {})
      @message.to = session[:test_out_to] || current_user.email_address
      if domain = @server.domains.verified.order(:name).first
        @message.from = "test@#{domain.name}"
      end
    end
    @message.subject = "Test Message at #{Time.zone.now.to_s(:long)}"
    @message.plain_body = "This is a message to test the delivery of messages through Postal."
  end

  def create
    if params[:direction] == 'incoming'
      session[:test_in_from] = params[:message][:from] if params[:message]
      @message = IncomingMessagePrototype.new(@server, request.ip, 'web-ui', params[:message])
      @message.attachments = [{:name => "test.txt", :content_type => "text/plain", :data => "Hello world!"}]
    else
      session[:test_out_to] = params[:message][:to] if params[:message]
      @message = OutgoingMessagePrototype.new(@server, request.ip, 'web-ui', params[:message])
    end
    if result = @message.create_messages
      if result.size == 1
        redirect_to_with_json organization_server_message_path(organization, @server, result.first.last[:id]), :notice => "Message was queued successfully"
      else
        redirect_to_with_json [:queue, organization, @server], :notice => "Messages queued successfully "
      end
    else
      respond_to do |wants|
        wants.html do
          flash.now[:alert] = "Your message could not be sent. Ensure that all fields are completed fully. #{result.errors.inspect}"
          render 'new'
        end
        wants.json do
          render :json => {:flash => {:alert => "Your message could not be sent. Please check all field are completed fully."}}
        end
      end

    end
  end

  def outgoing
    @searchable = true
    get_messages('outgoing')
    respond_to do |wants|
      wants.html
      wants.json { render :json => {
        :flash => flash.each_with_object({}) { |(type, message), hash| hash[type] = message},
        :region_html => render_to_string(:partial => 'index', :formats => [:html])
      }}
    end
  end

  def incoming
    @searchable = true
    get_messages('incoming')
    respond_to do |wants|
      wants.html
      wants.json { render :json => {
        :flash => flash.each_with_object({}) { |(type, message), hash| hash[type] = message},
        :region_html => render_to_string(:partial => 'index', :formats => [:html])
      }}
    end
  end

  def held
    get_messages('held')
  end

  def deliveries
    render :json => {:html => render_to_string(:partial => 'deliveries', :locals => {:message => @message})}
  end

  def html_raw
    render :html => @message.html_body_without_tracking_image.html_safe
  end

  def spam_checks
    @spam_checks = @message.spam_checks.sort_by { |s| s['score']}.reverse
  end

  def attachment
    if @message.attachments.size > params[:attachment].to_i
      attachment = @message.attachments[params[:attachment].to_i]
      send_data attachment.body, :content_type => attachment.mime_type, :disposition => 'download', :filename => attachment.filename
    else
      redirect_to attachments_organization_server_message_path(organization, @server, @message.id), :alert => "Attachment not found. Choose an attachment from the list below."
    end
  end

  def download
    if @message.raw_message
      send_data @message.raw_message, :filename => "Message-#{organization.permalink}-#{@server.permalink}-#{@message.id}.eml", :content_type => "text/plain"
    else
      redirect_to organization_server_message_path(organization, @server, @message.id), :alert => "We no longer have the raw message stored for this message."
    end
  end

  def retry
    if @message.raw_message?
      if @message.queued_message
        @message.queued_message.queue!
        flash[:notice] = "This message will be retried shortly."
      elsif @message.held?
        @message.add_to_message_queue(:manual => true)
        flash[:notice] = "This message has been released. Delivery will be attempted shortly."
      else
        @message.add_to_message_queue(:manual => true)
        flash[:notice] = "This message will be redelivered shortly."
      end
    else
      flash[:alert] = "This message is no longer available."
    end
    redirect_to_with_json organization_server_message_path(organization, @server, @message.id)
  end

  def cancel_hold
    @message.cancel_hold
    redirect_to_with_json organization_server_message_path(organization, @server, @message.id)
  end

  def remove_from_queue
    if @message.queued_message && !@message.queued_message.locked?
      @message.queued_message.destroy
    end
    redirect_to_with_json organization_server_message_path(organization, @server, @message.id)
  end

  def suppressions
    @suppressions = @server.message_db.suppression_list.all_with_pagination(params[:page])
  end

  def activity
    @entries = @message.activity_entries
  end

  private

  def get_messages(scope)
    if scope == 'held'
      options = {:where => {:held => 1}}
    else
      options = {:where => {:scope => scope, :spam => false}, :order => :timestamp, :direction => 'desc'}

      if @query = (params[:query] || session["msg_query_#{@server.id}_#{scope}"]).presence
        session["msg_query_#{@server.id}_#{scope}"] = @query
        qs = Postal::QueryString.new(@query)
        if qs.empty?
          flash.now[:alert] = "It doesn't appear you entered anything to filter on. Please double check your query."
        else
          @queried = true
          if qs[:order] == 'oldest-first'
            options[:direction] = 'asc'
          end

          options[:where][:rcpt_to] = qs[:to] if qs[:to]
          options[:where][:mail_from] = qs[:from] if qs[:from]
          options[:where][:status] = qs[:status] if qs[:status]
          options[:where][:token] = qs[:token] if qs[:token]

          if qs[:msgid]
            options[:where][:message_id] = qs[:msgid]
            options[:where].delete(:spam)
            options[:where].delete(:scope)
          end
          options[:where][:tag] = qs[:tag] if qs[:tag]
          options[:where][:id] = qs[:id] if qs[:id]
          options[:where][:spam] = true if qs[:spam] == 'yes' || qs[:spam] == 'y'
          if qs[:before] || qs[:after]
            options[:where][:timestamp] = {}
            if qs[:before]
              begin
                options[:where][:timestamp][:less_than] = get_time_from_string(qs[:before]).to_f
              rescue TimeUndetermined => e
                flash.now[:alert] = "Couldn't determine time for before from '#{qs[:before]}'"
              end
            end

            if qs[:after]
              begin
                options[:where][:timestamp][:greater_than] = get_time_from_string(qs[:after]).to_f
              rescue TimeUndetermined => e
                flash.now[:alert] = "Couldn't determine time for after from '#{qs[:after]}'"
              end
            end
          end
        end
      else
        session["msg_query_#{@server.id}_#{scope}"] = nil
      end
    end

    @messages = @server.message_db.messages_with_pagination(params[:page], options)
  end

  class TimeUndetermined < Postal::Error; end

  def get_time_from_string(string)
    begin
      if string =~ /\A(\d{2,4})\-(\d{2})\-(\d{2}) (\d{2})\:(\d{2})\z/
        time = Time.new($1.to_i, $2.to_i, $3.to_i, $4.to_i, $5.to_i)
      elsif string =~ /\A(\d{2,4})\-(\d{2})\-(\d{2})\z/
        time = Time.new($1.to_i, $2.to_i, $3.to_i, 0)
      else
        time = Chronic.parse(string, :context => :past)
      end
    rescue
    end

    if time.nil?
      raise TimeUndetermined, "Couldn't determine a suitable time from '#{string}'"
    else
      time
    end
  end

end

app/views/messages/_deliveries.html.haml
%ul.deliveryList
  - if message.queued_message && message.queued_message.locked?
    %li.deliveryList__item.deliveryList__item--header
      %p Message is currently being processed.
  - elsif message.queued_message && message.queued_message.retry_after
    %li.deliveryList__item.deliveryList__item--header
      %p This message will be retried automatically in #{distance_of_time_in_words_to_now message.queued_message.retry_after}.
      %p= link_to "Retry delivery now", retry_organization_server_message_path(organization, @server, message.id), :class => "button button--small", :remote => true, :method => :post
  - elsif message.held?
    %li.deliveryList__item.deliveryList__item--header
      %p
        This message has been held. By releasing the message, we will allow it to continue on its way to its destination.
        - if @message.hold_expiry
          It will be held until #{@message.hold_expiry.to_s(:long)}.
      %p.buttonSet
        = link_to "Release message", retry_organization_server_message_path(organization, @server, message.id), :class => "button button--small", :remote => true, :method => :post
        = link_to "Cancel hold", cancel_hold_organization_server_message_path(organization, @server, message.id), :class => "button button--small button--danger", :remote => true, :method => :post
  - elsif @server.mode == 'Development'
    %li.deliveryList__item.deliveryList__item--header
      %p This server is in development mode so this message can be redelivered as if it had just been received.
      %p= link_to "Redeliver message", retry_organization_server_message_path(organization, @server, message.id), :class => "button button--small", :remote => true, :method => :post
  - else
    %li.deliveryList__item.deliveryList__item--header
      %p This message can be redelivered as if it had just been received.
      %p= link_to "Redeliver message", retry_organization_server_message_path(organization, @server, message.id), :class => "button button--small", :remote => true, :method => :post

  - if message.deliveries.empty?
    %li.deliveryList__item
      .noData.noData--clean
        %h2.noData__text No delivery attempts yet.
  - else
    - for delivery in message.deliveries.reverse
      %li.deliveryList__item
        .deliveryList__top
          .deliveryList__time
            = delivery.timestamp.to_s(:long)
          .deliveryList__status
            - if delivery.sent_with_ssl == 1
              = image_tag 'icons/lock.svg', :class => 'deliveryList__secure'
            %span.label.label--large{:class => "label--messageStatus-#{delivery.status.underscore}"}= delivery.status.underscore.humanize
        - if delivery.details
          %p.deliveryList__error= format_delivery_details(@server, delivery.details)
        - if delivery.log_id || delivery.output
          = link_to "Show technical details", '#', :class => 'js-toggle js-tech-link deliveryList__techLink', :data => {:element => '.js-tech-link, .js-tech-output'}
          .deliveryList__error.deliveryList__error--output.js-tech-output.is-hidden
            %p.deliveryList__error--output-text= delivery.output
            - if delivery.time
              %p.deliveryList__error--output-ref Time: #{delivery.time}s
            - if delivery.log_id
              %p.deliveryList__error--output-ref Support Ref: #{delivery.log_id}
- if message.queued_message && !message.queued_message.locked?
  %p.deliveryList-removeLink= link_to "Remove from queue", remove_from_queue_organization_server_message_path(organization, @server, message.id), :method => :delete, :remote => true, :data => {:disable_with => "Removing...", :confirm => "Are you sure you wish to remove this message from the queue?"}, :class => "u-link"

app/views/messages/_header.html.haml
.navBar.navBar--secondary
  %ul
    %li.navBar__item= link_to "Outgoing Messages", [:outgoing, organization, @server, :messages], :class => ['navBar__link', active_nav == :outgoing ? 'is-active' : '']
    %li.navBar__item= link_to "Incoming Messages", [:incoming, organization, @server, :messages], :class => ['navBar__link', active_nav == :incoming ? 'is-active' : '']
    %li.navBar__item= link_to "Queue", [:queue, organization, @server], :class => ['navBar__link', active_nav == :queue ? 'is-active' : '']
    %li.navBar__item= link_to "Held", [:held, organization, @server, :messages], :class => ['navBar__link', active_nav == :held ? 'is-active' : '']
    %li.navBar__item= link_to "Send Message", [:new, organization, @server, :message], :class => ['navBar__link', active_nav == :new ? 'is-active' : '']
    %li.navBar__item= link_to "Suppressions", [:suppressions, organization, @server, :messages], :class => ['navBar__link', active_nav == :suppressions ? 'is-active' : '']

app/views/messages/_message_header.html.haml
.messageHeader
  .messageHeader__header{:class => "messageHeader__header--#{@message.scope}"}
    %p.messageHeader__status
      %span.label{:class => "label--messageStatus-#{@message.status.underscore}"}= @message.status.underscore.humanize
    %h2.messageHeader__subject
      = @message.subject || "No subject"

    .messageHeader__basicProperties
      %dl
        %dt From
        %dd
          - if @message.mail_from
            = link_to @message.mail_from || "[blank]", send("#{@message.scope}_organization_server_messages_path", organization, @server, :query => "from: #{@message.mail_from}"), :class => 'u-link'
          - else
            None

      %dl
        %dt To
        %dd
          - if @message.rcpt_to_return_path?
            %span.returnPathTag.returnPathTag--inMessageHeader= link_to "Return Path", send("#{@message.scope}_organization_server_messages_path", organization, @server, :query => "to: #{@message.rcpt_to}"), :class => 'u-link'
          - else
            = link_to @message.rcpt_to || "[blank]", send("#{@message.scope}_organization_server_messages_path", organization, @server, :query => "to: #{@message.rcpt_to}"), :class => 'u-link'
      %dl
        %dt Received
        %dd= @message.timestamp.in_time_zone.to_s(:long)

.navBar.navBar--tertiary
  %ul
    %li.navBar__item= link_to "Properties", organization_server_message_path(organization, @server, @message.id), :class => ['navBar__link', active_nav == :properties ? 'is-active' : '']
    %li.navBar__item= link_to "Activity", activity_organization_server_message_path(organization, @server, @message.id), :class => ['navBar__link', active_nav == :activity ? 'is-active' : '']
    %li.navBar__item= link_to "Headers", headers_organization_server_message_path(organization, @server, @message.id), :class => ['navBar__link', active_nav == :headers ? 'is-active' : '']
    %li.navBar__item= link_to "Spam Checks", spam_checks_organization_server_message_path(organization, @server, @message.id), :class => ['navBar__link', active_nav == :spam_checks ? 'is-active' : '']
    %li.navBar__item= link_to "Plain Text", plain_organization_server_message_path(organization, @server, @message.id), :class => ['navBar__link', active_nav == :plain ? 'is-active' : '']
    %li.navBar__item= link_to "HTML", html_organization_server_message_path(organization, @server, @message.id), :class => ['navBar__link', active_nav == :html ? 'is-active' : '']
    %li.navBar__item= link_to "Attachments", attachments_organization_server_message_path(organization, @server, @message.id), :class => ['navBar__link', active_nav == :attachments ? 'is-active' : '']
    - if @message.raw_message?
      %li.navBar__item= link_to "Download", download_organization_server_message_path(organization, @server, @message.id), :data => {:turbolinks => 'false'}, :class =>'navBar__link'

app/views/messages/_search.html.haml
= form_tag request.fullpath, :method => :get, :remote => true, :class => 'messageSearch', :enforce_utf8 => false do
  %p
    = link_to "Need help with filtering?", '#', :class => 'messageSearch__help js-toggle-helpbox'
    = text_field_tag 'query', @query, :class => 'messageSearch__input js-focus-on-f js-form-submit', :placeholder => "Filter messages...", :data => {:disable_with => 'Searching...'}

  .messageSearch__helpBox.is-hidden.js-helpbox
    .messageSearch__left
      %h3.messageSearch__helpBoxTitle
        Filtering your messages
      %p.messageSearch__helpBoxText
        You can filter your messages on a number of attributes. At present, it is not possible to
        search the content of your messages. To filter though, you can insert any of the strings
        as shown opposite into the box above and press enter.
    .messageSearch__right
      %dl.messageSearch__definition
        %dt to: rachel@example.com
        %dd Returns all mail addressed to the address provided.
      %dl.messageSearch__definition
        %dt from: tom@example.com
        %dd Returns all mail sent from to the address provided.
      %dl.messageSearch__definition
        %dt status: pending
        %dd Returns all messages with the status provided. The suitable statuses are: <code>pending</code>, <code>sent</code>, <code>held</code>, <code>softfail</code>, <code>hardfail</code> and <code>bounced</code>.
      %dl.messageSearch__definition
        %dt before: yyyy-mm-dd hh:mm
        %dd Returns any message received before the given timestamp.
      %dl.messageSearch__definition
        %dt after: yyyy-mm-dd hh:mm
        %dd Returns any message received after the given timestamp.
      %dl.messageSearch__definition
        %dt msgid:  57f3a85b35545@server01.mail
        %dd Returns any message with the given Message-ID header.
      %dl.messageSearch__definition
        %dt tag: password-reset
        %dd Returns any message tagged with the tag provided.
      %dl.messageSearch__definition
        %dt spam: yes
        %dd By default, spam is not shown in results. To show spam instead of non-spam, just add this to the query.
      %dl.messageSearch__definition
        %dt order: oldest-first
        %dd By default, newest messages are shown first. To show oldest messages first, you can add this.

app/views/messages/activity.html.haml
- page_title << @server.name
- page_title << "Messages"
- page_title << "Message ##{@message.id}"
- page_title << "Activity"
= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :messages
= render 'header', :active_nav => @message.scope.to_sym
= render 'message_header', :active_nav => :activity
.pageContent.pageContent--compact
  %ul.messageActivity
    - for entry in @entries.reverse
      - if entry.is_a?(Postal::MessageDB::Delivery)
        %li.messageActivity__event
          %p.messageActivity__timestamp= entry.timestamp.to_s(:long)
          .messageActivity__details.messageActivity--detailsDelivery
            %p.messageActivity__subject
              =# entry.status.underscore.humanize
              %span.label.label--large{:class => "label--messageStatus-#{entry.status.underscore}"}= entry.status.underscore.humanize

            %p.messageActivity__extra= entry.details

      - elsif entry.is_a?(Postal::MessageDB::Click)
        %li.messageActivity__event
          %p.messageActivity__timestamp= entry.timestamp.to_s(:long)
          .messageActivity__details.messageActivity--detailsClick
            %p.messageActivity__subject Click for #{entry.url}
            %p.messageActivity__extra Clicked from #{entry.ip_address} (#{entry.user_agent})

      - elsif entry.is_a?(Postal::MessageDB::Load)
        %li.messageActivity__event
          %p.messageActivity__timestamp= entry.timestamp.to_s(:long)
          .messageActivity__details.messageActivity--detailsLoad
            %p.messageActivity__subject Message Viewed
            %p.messageActivity__extra Opened from #{entry.ip_address} (#{entry.user_agent})

    %li.messageActivity__event
      %p.messageActivity__timestamp= @message.timestamp.to_s(:long)
      .messageActivity__details
        %p.messageActivity__subject
          Message received by Postal
        %p.messageActivity__extra
          - if @message.credential
            Received using the #{@message.credential.name} #{@message.credential.type} credential.
          - if @message.received_with_ssl == 1
            Connection secured with SSL.

app/views/messages/headers.html.haml
- page_title << @server.name
- page_title << "Messages"
- page_title << "Message ##{@message.id}"
- page_title << "Headers"
= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :messages
= render 'header', :active_nav => @message.scope.to_sym
= render 'message_header', :active_nav => :headers

- if @message.headers.empty?
  .pageContent.pageContent--compact
    .noData.noData--clean
      %h2.noData__title There are no headers for this message.
      %p.noData__text
        This means that we no longer store the raw data for this e-mail.

- else
  .pageContent
    .headersList
      - for key, values in @message.headers
        - for value in values
          %dl.headersList__item
            %dt= key
            %dd= value

app/views/messages/held.html.haml
- page_title << @server.name
- page_title << "Messages"
- page_title << "Held"
= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :messages
= render 'header', :active_nav => :held
- if @messages.empty? && !@queried
  .pageContent--compact
    .noData.noData--clean
      %h2.noData__title You haven't got any held messages.
      %p.noData__text
        You haven't sent any messages through this mail server yet. Not to worry though
        they'll start appearing here as soon as you start sending them.
- else
  = render 'index'

app/views/messages/html.html.haml
- page_title << @server.name
- page_title << "Messages"
- page_title << "Message ##{@message.id}"
- page_title << "HTML"
= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :messages
= render 'header', :active_nav => @message.scope.to_sym
= render 'message_header', :active_nav => :html
- if @message.html_body.blank?
  .pageContent.pageContent--compact
    .noData.noData--clean
      %h2.noData__title There's no HTML body for this message.
      %p.noData__text
        This means that we no longer store the raw data for this e-mail
        or the e-mail didn't include a HTML part.
- else
  %iframe{:width => "100%", :height => "100%", :src => html_raw_organization_server_message_path(organization, @server, @message.id)}

app/views/messages/outgoing.html.haml
- page_title << @server.name
- page_title << "Messages"
- page_title << "Outgoing"
= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :messages
= render 'header', :active_nav => :outgoing
- if @messages[:records].empty? && !@queried
  .pageContent--compact
    .noData.noData--clean
      %h2.noData__title No messages have been sent yet.
      %p.noData__text
        You haven't sent any messages through this mail server yet. Not to worry though
        they'll start appearing here as soon as you start sending them.
- else
  = render 'index'

app/views/messages/show.html.haml
- page_title << @server.name
- page_title << "Messages"
- page_title << "Message ##{@message.id}"
= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :messages
= render 'header', :active_nav => @message.scope.to_sym
= render 'message_header', :active_nav => :properties
.pageContent
  .messagePropertiesPage
    .messagePropertiesPage__left
      .messagePropertiesPage__propertyPair
        %dl.messagePropertiesPage__property
          %dt Spam Status
          %dd
            = link_to spam_checks_organization_server_message_path(organization, @server, @message.id) do
              %span.label.label--large{:class => "label--spamStatus-#{@message.spam_status.underscore}"}= @message.spam_status.underscore.humanize
        %dl.messagePropertiesPage__property
          %dt Tag
          %dd= @message.tag ? link_to(@message.tag, send("#{@message.scope}_organization_server_messages_path", organization, @server, :query => "tag: #{@message.tag}"), :class => "u-link") : "Not tagged"
      .messagePropertiesPage__propertyPair
        %dl.messagePropertiesPage__property
          %dt Raw Message
          %dd= @message.raw_message? ? "Available" : "Removed"
        %dl.messagePropertiesPage__property
          %dt Message Size
          %dd= @message.size ? number_to_human_size(@message.size) : "n/a"

      .messagePropertiesPage__propertyPair
        - if @message.scope == 'incoming'
          %dl.messagePropertiesPage__property
            %dt Route
            %dd
              - if @message.route
                = link_to @message.route.name, [:edit, organization, @server, @message.route], :class => "u-link"
              - else
                Unknown Route
          %dl.messagePropertiesPage__property
            %dt Domain
            %dd
              - if @message.domain
                = link_to @message.domain.name, [organization, @server, :domains], :class => "u-link"
              - else
                Unknown Domain
        - else
          %dl.messagePropertiesPage__property
            %dt Credential
            %dd
              - if @message.credential
                = link_to @message.credential.name, [:edit, organization, @server, @message.credential], :class => "u-link"
              - else
                Unknown Credential
          %dl.messagePropertiesPage__property
            %dt Domain
            %dd
              - if @message.domain
                = link_to @message.domain.name, [organization, @server, :domains], :class => "u-link"
              - else
                Unknown Domain
      - if @message.threat == 1
        %dl.messagePropertiesPage__property
          %dt Threat
          %dd= @message.threat_details
      %dl.messagePropertiesPage__property
        %dt Message ID
        %dd= @message.message_id || "No message ID"
      - unless @message.received_with_ssl.nil?
        %dl.messagePropertiesPage__property
          %dt Transport Security
          - if @message.received_with_ssl == 1
            %dd.messagePropertiesPage__property--locked Received over a SSL connection
          - else
            %dd Not received with SSL

    .messagePropertiesPage__right
      = render 'deliveries', :message => @message

app/views/messages/suppressions.html.haml
- page_title << @server.name
- page_title << "Messages"
- page_title << "Suppression List"
= render 'servers/sidebar', :active_server => @server
= render 'servers/header', :active_nav => :messages
= render 'header', :active_nav => :suppressions
.pageContent.pageContent--compact
  - if @suppressions[:records].empty?
    .noData.noData--clean
      %h2.noData__title No addresses on the suppression list.
      %p.noData__text
        When messages cannot be delivered, addresses are added to the suppression list which stops
        future messages to the same recipient being sent through.
  - else
    %p.pageContent__intro.u-margin
      When messages cannot be delivered, addresses are added to the suppression list which stops
      future messages to the same recipient being sent through. Recipients are removed from the list after #{Postal.config.general.suppression_list_removal_delay} days.
    %ul.suppressionList
      - for suppression in @suppressions[:records]
        %li.suppressionList__item
          .suppressionList__left
            %p.suppressionList__address= link_to suppression['address'], outgoing_organization_server_messages_path(organization, @server, :query => "to: #{suppression['address']}")
            %p.suppressionList__reason= suppression['reason'].capitalize
          .suppressionList__right
            %p.suppressionList__timestamp Added #{Time.zone.at(suppression['timestamp']).to_s(:long)}
            %p.suppressionList__timestamp
              Expires #{Time.zone.at(suppression['keep_until']).to_s(:long)}
              - if suppression['keep_until'] < Time.now.to_f
                %span.u-red expired
    = render 'shared/message_db_pagination', :data => @suppressions, :name => "suppression"