config/routes.rb
Rails.application.routes.draw do

  scope "org/:org_permalink", :as => 'organization' do
    resources :domains, :only => [:index, :new, :create, :destroy] do
      match :verify, :on => :member, :via => [:get, :post]
      get :setup, :on => :member
      post :check, :on => :member
    end
    resources :servers, :except => [:index] do
      resources :domains, :only => [:index, :new, :create, :destroy] do
        match :verify, :on => :member, :via => [:get, :post]
        get :setup, :on => :member
        post :check, :on => :member
      end
      resources :track_domains do
        post :toggle_ssl, :on => :member
        post :check, :on => :member
      end
      resources :credentials
      resources :routes
      resources :http_endpoints
      resources :smtp_endpoints
      resources :address_endpoints
      resources :ip_pool_rules
      resources :messages do
        get :incoming, :on => :collection
        get :outgoing, :on => :collection
        get :held, :on => :collection
        get :activity, :on => :member
        get :plain, :on => :member
        get :html, :on => :member
        get :html_raw, :on => :member
        get :attachments, :on => :member
        get :headers, :on => :member
        get :attachment, :on => :member
        get :download, :on => :member
        get :spam_checks, :on => :member
        post :retry, :on => :member
        post :cancel_hold, :on => :member
        get :suppressions, :on => :collection
        delete :remove_from_queue, :on => :member
        get :deliveries, :on => :member
      end
      resources :webhooks do
        get :history, :on => :collection
        get 'history/:uuid', :on => :collection, :action => 'history_request', :as => 'history_request'
      end
      get :limits, :on => :member
      get :retention, :on => :member
      get :queue, :on => :member
      get :spam, :on => :member
      get :delete, :on => :member
      get 'help/outgoing' => 'help#outgoing'
      get 'help/incoming' => 'help#incoming'
      get :advanced, :on => :member
      post :suspend, :on => :member
      post :unsuspend, :on => :member
    end

    resources :ip_pool_rules
    resources :ip_pools, :controller => 'organization_ip_pools' do
      put :assignments, :on => :collection
    end
    root 'servers#index'
    get 'settings' => 'organizations#edit'
    patch 'settings' => 'organizations#update'
    get 'delete' => 'organizations#delete'
    delete 'delete' => 'organizations#destroy'
  end

  resources :organizations, :except => [:index]
  resources :users
  resources :ip_pools do
    resources :ip_addresses
  end

  get 'settings' => 'user#edit'
  patch 'settings' => 'user#update'
  post 'persist' => 'sessions#persist'

  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  get 'login/token' => 'sessions#create_with_token'
  delete 'logout' => 'sessions#destroy'
  match 'login/reset' => 'sessions#begin_password_reset', :via => [:get, :post]
  match 'login/reset/:token' => 'sessions#finish_password_reset', :via => [:get, :post]


  get 'ip' => 'sessions#ip'

  root 'organizations#index'
end

app/models/organization_ip_pool.rb
# == Schema Information
#
# Table name: organization_ip_pools
#
#  id              :integer          not null, primary key
#  organization_id :integer
#  ip_pool_id      :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class OrganizationIPPool < ApplicationRecord
  belongs_to :organization
  belongs_to :ip_pool
end

app/controllers/organization_ip_pools_controller.rb
class OrganizationIPPoolsController < ApplicationController

  include WithinOrganization
  before_action :admin_required, :only => [:assignments]

  def index
    @ip_pools = organization.ip_pools.order(:name)
  end

  def assignments
    organization.ip_pool_ids = params[:ip_pools]
    organization.save!
    redirect_to [organization, :ip_pools], :notice => "Organization IP pools have been updated successfully"
  end

end

app/views/organization_ip_pools/_nav.html.haml
.navBar.navBar--secondary
  %ul
    %li.navBar__item= link_to "IP Pools", organization_ip_pools_path(organization), :class => ['navBar__link', active_nav == :ips ? 'is-active' : '']
    %li.navBar__item= link_to "Rules", organization_ip_pool_rules_path(organization), :class => ['navBar__link', active_nav == :rules ? 'is-active' : '']

app/views/organization_ip_pools/index.html.haml
- page_title << "IPs"
- page_title << "Rules"

.pageHeader
  %h1.pageHeader__title
    %span.pageHeader__titlePrevious
      = @organization.name
      &rarr;
    Dedicated IPs

= render 'organizations/nav', :active_nav => :ips
= render 'nav', :active_nav => :ips

.pageContent.pageContent--compact
  - if current_user.admin?
    %p.pageContent__intro.u-margin
      Choose which IP pools this organization will have access to send mail using. Organization
      users will be able to choose from any of the pools chosen below. Admins can override on a per
      server basis if required.
    = form_tag [:assignments, @organization, :ip_pools], :method => :put do
      %ul.checkboxList.u-margin
        - for ip_pool in IPPool.order(:name)
          %li.checkboxList__item
            .checkboxList__checkbox= check_box_tag "ip_pools[]", ip_pool.id, @organization.ip_pools.include?(ip_pool), :id => "ip_pool_#{ip_pool.id}"
            .checkboxList__label
              = label_tag "ip_pool_#{ip_pool.id}", ip_pool.name, :class => 'checkboxList__actualLabel'
      %p= submit_tag "Save IP pool assignment", :class => 'button button--positive'
  - else
    - if @ip_pools.empty?
      .noData.noData--clean
        - if @server.nil?
          %h2.noData__title You don't have any assigned IP addresses.
          %p.noData__text
            Once you've been assigned IP addresses they will appear here. You can then use them in rules and
            for servers.
    - else
      .ipList
        - for ip_pool in @ip_pools
          .ipList__item
            %p.ipList__name= ip_pool.name
            %ul.ipList__addressList
              %li.ipList__address.ipList__address--header
                %p.ipList__ipv4 IPv4 Address
                %p.ipList__ipv6 IPv6 Address
                %p.ipList__hostname Hostname

              - for address in ip_pool.ip_addresses
                %li.ipList__address
                  %p.ipList__ipv4= address.ipv4
                  %p.ipList__ipv6= address.ipv6
                  %p.ipList__hostname= address.hostname